# Generated by Django 4.0.5 on 2022-07-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='rep',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='rest',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='set',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
