# Generated by Django 4.0.3 on 2022-04-25 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
        ('program', '0002_program_last_weight_alter_program_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='gym',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gym.gymtracker'),
        ),
    ]
