# Generated by Django 4.0.3 on 2022-04-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_alter_program_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='day',
            field=models.CharField(choices=[('day1', 'Day 1'), ('day2', 'Day 2'), ('day3', 'Day 3'), ('day4', 'Day 4'), ('day5', 'Day 5'), ('day6', 'Day 6'), ('day7', 'Day 7'), ('day8', 'Day 8'), ('day9', 'Day 9'), ('day10', 'Day 10')], default='day1', max_length=120),
        ),
    ]
